# Generated by Django 5.2.10 on 2026-01-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_featured_image'),
        ('products', '0002_initial'),
    ]

    operations = [
    ]
