# Generated by Django 5.2.10 on 2026-01-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_user_id_de49e5_idx',
            old_name='user_activi_user_id_9b7c98_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='user_activi_session_29b078_idx',
            old_name='user_activi_session_ca8c0a_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
